### ISSUE TITLE
no compila

### ISSUE THREAD

**Issue by vroddon** [mnavasloro/ixasrl#3]
@mnavasloro , esto no compila.
[ERROR] Failed to execute goal on project CoreNLPtest: Could not resolve dependencies for project oeg.tagger:CoreNLPtest:jar:1.0: Failed to collect dependencies at local:srl:jar:1.0: Failed to read artifact descriptor for local:srl:jar:1.0: Could not transfer artifact local:srl:pom:1.0 from/to github (https://maven.pkg.github.com/oeg-upm): Failed to transfer file: https://maven.pkg.github.com/oeg-upm/local/srl/1.0/srl-1.0.pom. Return code is: 400 , ReasonPhrase:Bad Request. -> [Help 1]

**Comment by mnavasloro** [comment]
ayer compilaba y yo no he tocado el código... siendo dependencias, no será por el todo.bat?

**Comment by vroddon** [comment]
Indeed. Te ruego disculpes mi olvido.
